### ISSUE TITLE
UnityProjectSettingsExtensions.SetBuildTarget(this UnityProjectSettings, UnityBuildTarget) is broken

### ISSUE THREAD

**Issue by razenpok** [nuke-build/nuke#1231]
### Usage Information

7.0.3

### Description

`SetBuildTarget(this UnityProjectSettings, UnityBuildTarget)` is conflicting with an extension `SetBuildTarget(this UnityProjectSettings, string)`

"CS0121: The call is ambiguous between the following methods" error

### Reproduction Steps

```csharp
UnityTasks.Unity(_ => _.SetBuildTarget(UnityBuildTarget.Android));
```

### Expected Behavior

This code snippet compiles

### Actual Behavior

This code snippet doesn't compile

### Regression?

Worked in 7.0.2
Is broken after the rework in #1194

### Known Workarounds

I've added a new extension to fix the compilation error

```csharp
public static class UnityProjectSettingsExtensions
{
    [Pure]
    public static T SetBuildTargetFixed<T>(this T toolSettings, UnityBuildTarget buildTarget)where T : UnityProjectSettings
    {
        return toolSettings.SetBuildTarget(buildTarget.ToString());
    }
}
```

### Could you help with a pull-request?

No

**Comment by razenpok** [comment]
By the way, the original method works with `UnityProjectSettings` type directly, while it should work with `T : UnityProjectSettings` instead

https://github.com/nuke-build/nuke/blob/afd2da863e61b69f127955eaf8658fed19a1aaf5/source/Nuke.Common/Tools/Unity/UnityProjectSettingsExtensions.cs#L18

**Comment by matkoch** [comment]
@kkopanski could you take a look?

**Comment by razenpok** [comment]
Oh, sorry, the extension `SetBuildTarget(this UnityProjectSettings, string)` was there in 7.0.2

But, for some reason, the code in the repro steps wouldn't compile in 7.0.3

**Comment by kkopanski** [comment]
> @kkopanski could you take a look?

I'm on it.
Sorry for inconvenience.

**Comment by kkopanski** [comment]
Well... compile error comes from `Enumeration` implicit conversion to string which I have missed.
Rework to generic function works as expected:
- no implicit cast error
- visibility of overloads in code completion

Once again sorry for missing this earlier.

**Comment by matkoch** [comment]
@kkopanski please put your sorry's away. There's absolutely no need for that.

I only tagged you because you made the latest changes :)

**Comment by kkopanski** [comment]
Tag me always in this kind of situations 😄
