### ISSUE TITLE
What happend to the `Nuke.Common.Configuration` class?

### ISSUE THREAD

**Issue by bert2** [nuke-build/nuke#598]
### Description

Since I updated Nuke.Common from 0.24.11 to 0.25.0, I'm getting a compiler error:
> CS0234: The type or namespace name 'Configuration' could not be found (are you missing a using directive or an assembly reference?)

```csharp
// ...

class Build : NukeBuild {
    public static int Main() => Execute<Build>(x => x.Compile);

    [Parameter("Configuration to build - Optional (default: 'Release')")]
    readonly Nuke.Common.Configuration Configuration = Configuration.Release; // ERROR CS0234

    // ...
```

I can see in the [merge commit](https://github.com/nuke-build/nuke/commit/af2bd97550d1c52a8cfa79fb5098a67911cd0145) that `Nuke.Common.Configuration` has been [deleted](https://github.com/nuke-build/nuke/commit/af2bd97550d1c52a8cfa79fb5098a67911cd0145#diff-7aa31d722979ba6353b6837cca4796443ed70829d23efb364a523fd42316e229) from the `source` directory and [moved](https://github.com/nuke-build/nuke/commit/af2bd97550d1c52a8cfa79fb5098a67911cd0145#diff-474a8869a56b1c787ce449d8e01c7a6430c5ed868c7e1ce728e44af7e27ef0c1) into the `build` directory of the repo.

The [changelog](https://github.com/nuke-build/nuke/blob/master/CHANGELOG.md) however has no mention of this and it is unclear to me how I am supposed to fix this.

**Comment by matkoch** [comment]
Just copy it over.

**Comment by bert2** [comment]
Oh, I see. Nuke doesn't actually rely on this type and I can make that `[Parameter]` a plain `string`.

**Comment by matkoch** [comment]
If you like, yes. It’s just there for shell completion.
